In [ ]:
import glob
import os

import pandas as pd  # type: ignore


def load_input(input_directory):
    """Load text files in 'input_directory/'"""
    #
    # Lea los archivos de texto en la carpeta input/ y almacene el contenido en
    # un DataFrame de Pandas. Cada línea del archivo de texto debe ser una
    # entrada en el DataFrame.
    #
    files = glob.glob(f"{input_directory}/*")
    dataframes = [
        pd.read_csv(
            file,
            header=None,
            delimiter="\t",
            names=["line"],
            index_col=None,
        )
        for file in files
    ]

    dataframe = pd.concat(dataframes, ignore_index=True)

    return dataframe

In [6]:
x = load_input('../files/input/')

In [7]:
x

                                                 line
0   Analytics refers to the systematic computation...
1   or statistics, typically for the purpose of ga...
2   making informed decisions, and discovering pat...
3   encompasses a broad range of techniques and me...
4   extracting meaningful information from raw dat...
5   processes such as data collection, cleaning, t...
6   modeling, and interpretation. Analytics can be...
7   various domains including business, finance, h...
8   and science, among others, to uncover hidden p...
9   future outcomes, optimize processes, and drive...
10  decision-making. It relies heavily on mathemat...
11  principles, as well as computational tools and...
12  derive actionable insights from complex datasets.
13  Analytics is the systematic computational anal...
14  statistics. It involves the discovery, interpr...
15  communication of meaningful patterns within da...
16  aimed at extracting insights to support decisi...
17  process typically involves various techniques,...
18  statistical analysis, predictive modeling, dat...
19  machine learning algorithms. Analytics spans a...
20  domains, including business, finance, healthca...
21  offering valuable insights to optimize process...
22  trends, forecast outcomes, and mitigate risks....
23  organizations to make data-driven decisions, u...
24  patterns, and gain a competitive edge in their...
25  industries. With the exponential growth of dat...
26  analytics has become increasingly essential fo...
27  actionable intelligence from vast and complex ...
28  driving innovation, and fostering informed dec...
29  Business intelligence (BI) refers to the techn...
30  and practices utilized by organizations to ana...
31  raw data in order to make informed business de...
32  collecting, organizing, and transforming data ...
33  insights that drive strategic planning, operat...
34  and competitive advantages. BI encompasses var...
35  including data mining, data visualization, sta...
36  and predictive modeling, all aimed at uncoveri...
37  and correlations within data sets. By harnessi...
38  methodologies, businesses can gain a deeper un...
39  operations, customer behaviors, market dynamic...
40  opportunities or risks. Ultimately, business i...
41  organizations to optimize performance, mitigat...
42  swiftly to changing market conditions, fosteri...
43  innovation in today's dynamic business landscape.
44  Data science is an interdisciplinary field tha...
45  scientific methods, algorithms, processes, and...
46  to extract knowledge and insights from structu...
47  unstructured data. It encompasses various tech...
48  from statistics, mathematics, computer science...
49  domain-specific knowledge to analyze complex d...
50  Data scientists leverage programming languages...
51  Python, R, and SQL, along with tools such as m...
52  learning and data visualization, to uncover pa...
53  trends, and correlations within data. They pla...
54  role in informing decision-making processes ac...
55  industries, from business and healthcare to fi...
56  technology. By harnessing the power of data, d...
57  facilitates predictive modeling, optimization,...
58  development of data-driven strategies to addre...
59                   challenges and drive innovation.

In [8]:
def clean_text(dataframe):
    """Text cleaning"""
    #
    # Elimine la puntuación y convierta el texto a minúsculas.
    #
    dataframe = dataframe.copy()
    dataframe["line"] = dataframe["line"].str.lower()
    dataframe["line"] = (
        dataframe["line"]
        .str.replace(",", "")
        .str.replace(
            ".",
            "",
        )
    )
    return dataframe

In [10]:
texto_limpio = clean_text(x)

In [ ]:
texto_limpio

                                                 line
0   analytics refers to the systematic computation...
1   or statistics typically for the purpose of gai...
2   making informed decisions and discovering patt...
3   encompasses a broad range of techniques and me...
4   extracting meaningful information from raw dat...
5   processes such as data collection cleaning tra...
6   modeling and interpretation analytics can be a...
7   various domains including business finance hea...
8   and science among others to uncover hidden pat...
9   future outcomes optimize processes and drive s...
10  decision-making it relies heavily on mathemati...
11  principles as well as computational tools and ...
12   derive actionable insights from complex datasets
13  analytics is the systematic computational anal...
14  statistics it involves the discovery interpret...
15  communication of meaningful patterns within da...
16  aimed at extracting insights to support decisi...
17  process typically involves various techniques ...
18  statistical analysis predictive modeling data ...
19  machine learning algorithms analytics spans ac...
20  domains including business finance healthcare ...
21  offering valuable insights to optimize process...
22  trends forecast outcomes and mitigate risks it...
23  organizations to make data-driven decisions un...
24  patterns and gain a competitive edge in their ...
25  industries with the exponential growth of data...
26  analytics has become increasingly essential fo...
27  actionable intelligence from vast and complex ...
28  driving innovation and fostering informed deci...
29  business intelligence (bi) refers to the techn...
30  and practices utilized by organizations to ana...
31  raw data in order to make informed business de...
32  collecting organizing and transforming data in...
33  insights that drive strategic planning operati...
34  and competitive advantages bi encompasses vari...
35  including data mining data visualization stati...
36  and predictive modeling all aimed at uncoverin...
37  and correlations within data sets by harnessin...
38  methodologies businesses can gain a deeper und...
39  operations customer behaviors market dynamics ...
40  opportunities or risks ultimately business int...
41  organizations to optimize performance mitigate...
42  swiftly to changing market conditions fosterin...
43   innovation in today's dynamic business landscape
44  data science is an interdisciplinary field tha...
45  scientific methods algorithms processes and sy...
46  to extract knowledge and insights from structu...
47  unstructured data it encompasses various techn...
48   from statistics mathematics computer science and
49  domain-specific knowledge to analyze complex d...
50  data scientists leverage programming languages...
51  python r and sql along with tools such as mach...
52  learning and data visualization to uncover pat...
53  trends and correlations within data they play ...
54  role in informing decision-making processes ac...
55  industries from business and healthcare to fin...
56  technology by harnessing the power of data dat...
57  facilitates predictive modeling optimization a...
58  development of data-driven strategies to addre...
59                    challenges and drive innovation

In [15]:
a = texto_limpio["line"].str.split()

In [18]:
a.explode("line")

0       analytics
1          refers
2              to
3             the
4      systematic
          ...
451    real-world
452    challenges
453           and
454         drive
455    innovation
Name: line, Length: 456, dtype: object